FootballLeague.App/Areas/Admin/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FootballLeague.Common.Models;
using FootballLeague.Common.ViewModels;
using FootballLeague.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FootballLeague.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MatchController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMatchService _matchService;
        private readonly ITeamService _teamService;

        public MatchController(IMapper mapper, IMatchService matchService, ITeamService teamService)
        {
            this._mapper = mapper;
            this._matchService = matchService;
            this._teamService = teamService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add()
        {
            return this.View(new MatchViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add(MatchViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var match = this._mapper.Map<Match>(model);
            var homeTeam = await this._teamService.Get(match.HomeTeamId);
            var awayTeam = await this._teamService.Get(match.AwayTeamId);

            await this._matchService.Create(match);
            await this._teamService.UpdatePointsNewMatch(homeTeam, awayTeam, match.HomeGoals, match.AwayGoals);

            return this.RedirectToAction("Table", "Team", new { area = "Admin" });
        }

        [HttpGet]
        [Route("/Match/List")]
        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> List()
        {
            var matches = await this._matchService.List();
            var models = this._mapper.Map<IList<Match>, IList<MatchViewModel>>(matches)
                .OrderByDescending(x => x.Date)
                .ToList();

            return this.View(models);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var match = await this._matchService.Get(id);
            var model = this._mapper.Map<MatchViewModel>(match);
            return this.View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(MatchViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var matchPastState = await this._matchService.Get(model.Id);
            var pastHomeGoals = matchPastState.HomeGoals;
            var pastAwayGoals = matchPastState.AwayGoals;
            var matchNewState = matchPastState;
            var homeTeam = await this._teamService.Get(model.HomeTeamId);
            var awayTeam = await this._teamService.Get(model.AwayTeamId);

            matchNewState.HomeGoals = model.HomeGoals;
            matchNewState.AwayGoals = model.AwayGoals;
            matchNewState.Date = model.Date;

            await this._matchService.Update(matchNewState);
            await this._teamService
                .UpdatePointsRemovedMatch(homeTeam, awayTeam, pastHomeGoals, pastAwayGoals);
            await this._teamService
                .UpdatePointsNewMatch(homeTeam, awayTeam, model.HomeGoals, model.AwayGoals);
            

            return this.RedirectToAction("Table", "Team", new { area = "Admin" });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(MatchViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var match = this._mapper.Map<MatchViewModel, Match>(model);
            var homeTeam = await this._teamService.Get(model.HomeTeamId);
            var awayTeam = await this._teamService.Get(model.AwayTeamId);

            match.IsDeleted = true;

            await this._teamService
                .UpdatePointsRemovedMatch(homeTeam, awayTeam, model.HomeGoals, model.AwayGoals);
            await this._matchService.Update(match);

            return this.RedirectToAction("Table", "Team", new { area = "Admin" });
        }
    }
}

FootballLeague.App/Areas/Admin/Views/Match/Add.cshtml
@model FootballLeague.Common.ViewModels.MatchViewModel
@{
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Add Match</h2>
<div class="row">
    <div class="col-md-6">
        <section>
            <form asp-area="Admin" asp-controller="Match" asp-action="Add" method="post">
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Date"></label>
                    <input type="date" asp-for="Date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="HomeTeamId">Home Team</label>
                    <select id="home-teams" class="form-control"
                            asp-for="HomeTeamId">
                        <option>Select home team...</option>
                    </select>
                    <span asp-validation-for="HomeTeamId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AwayTeamId">Away Team</label>
                    <select id="away-teams" class="form-control"
                            asp-for="AwayTeamId">
                        <option>Select away team...</option>
                    </select>
                    <span asp-validation-for="AwayTeamId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label asp-for="HomeGoals">Home Goals</label>
                            <input asp-for="HomeGoals" type="number" class="form-control" />
                        </div>
                        <div class="col-md-3">
                            <label asp-for="AwayGoals">Away Goals</label>
                            <input asp-for="AwayGoals" type="number" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="form-group pull-right">
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
            </form>
        </section>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        let homeTeamId;
        let awayTeamId;
        let availableTeams;

        $(document).ready(function () {
            $.ajax({
                url: '/Admin/Team/GetTeams',
                method: 'GET',
            }).then(function (teams) {
                availableTeams = teams;
                $('#home-teams').empty();
                $('#away-teams').empty();

                $('#home-teams').append($('<option>')
                    .text('Select home team...')
                    .prop('selected', 'selected'));

                $('#away-teams').append($('<option>')
                    .text('Select away team...')
                    .prop('selected', 'selected'));

                $.each(teams, function (index, value) {
                    let currentTeam = teams[index];
                    let currentOption = $('<option>')
                        .text(currentTeam.name)
                        .val(currentTeam.id);

                    $('#home-teams, #away-teams').append($(currentOption));
                });
            });
        });

        $('#home-teams').change(function () {
            homeTeamId = Number($(this).find('option:selected').val());

            if (awayTeamId === null) {
                $('#away-teams').empty();
                $('#away-teams').append($('<option>')
                    .text('Select away team...')
                    .prop('selected', 'selected'));

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== homeTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#away-teams').append($(currentOption));
                    }
                });
            } else {
                $('#away-teams').empty();

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== homeTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#away-teams').append($(currentOption));
                    }
                });
                $('#away-teams').find(`option[value=${awayTeamId}]`).prop('selected', 'selected');
            }
        });

        $('#away-teams').change(function () {
            awayTeamId = Number($(this).find('option:selected').val());

            if (homeTeamId === null) {
                $('#home-teams').empty();
                $('#home-teams').append($('<option>')
                    .text('Select home team...')
                    .prop('selected', 'selected'));

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== awayTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#home-teams').append($(currentOption));
                    }
                });
            } else {
                $('#home-teams').empty();

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== awayTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#home-teams').append($(currentOption));
                    }
                });
                $('#home-teams').find(`option[value=${homeTeamId}]`).prop('selected', 'selected');
            }
        });
    </script>
}

FootballLeague.App/Areas/Admin/Views/Match/Edit.cshtml
@model FootballLeague.Common.ViewModels.MatchViewModel
@{
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Edit Match</h2>
<div class="row">
    <div class="col-md-6">
        <section>
            <form asp-area="Admin" asp-controller="Match" asp-action="Edit" method="post">
                <hr />
                @Html.HiddenFor(x => x.Id)
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Date"></label>
                    <input type="date" asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="HomeTeamId">Home Team</label>
                    <select id="home-teams" class="form-control"
                            asp-for="HomeTeamId" readonly="readonly">
                    </select>
                    <span asp-validation-for="HomeTeamId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AwayTeamId">Away Team</label>
                    <select id="away-teams" class="form-control"
                            asp-for="AwayTeamId" readonly="readonly">
                    </select>
                    <span asp-validation-for="AwayTeamId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label asp-for="HomeGoals">Home Goals</label>
                            <input asp-for="HomeGoals" type="number" class="form-control" />
                        </div>
                        <div class="col-md-3">
                            <label asp-for="AwayGoals">Away Goals</label>
                            <input asp-for="AwayGoals" type="number" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="form-group pull-right">
                    <button type="submit" class="btn btn-warning">Edit</button>
                    <button type="button" data-toggle="modal" data-target="#delete-modal" data-backdrop="static" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </section>
    </div>
</div>

<div id="delete-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete Team</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this match?</p>
            </div>
            <div class="modal-footer">
                <form asp-area="Admin" asp-controller="Match" asp-action="Delete" method="post">
                    @Html.HiddenFor(x => x.Id)
                    @Html.HiddenFor(x => x.HomeTeamId)
                    @Html.HiddenFor(x => x.AwayTeamId)
                    @Html.HiddenFor(x => x.Date)
                    @Html.HiddenFor(x => x.HomeGoals)
                    @Html.HiddenFor(x => x.AwayGoals)
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        let homeTeamId;
        let awayTeamId;
        let availableTeams;

        $(document).ready(function () {
            $.ajax({
                url: '/Admin/Team/GetTeams',
                method: 'GET',
            }).then(function (teams) {
                availableTeams = teams;
                let selectedHomeTeamId = '@Model.HomeTeamId';
                let selectedAwayTeamId = '@Model.AwayTeamId';

                $('#home-teams').empty();
                $('#away-teams').empty();

                $.each(teams, function (index, value) {
                    let currentTeam = teams[index];
                    let currentOption = $('<option>')
                        .text(currentTeam.name)
                        .val(currentTeam.id);

                    $('#home-teams, #away-teams').append($(currentOption));
                });

                $('#home-teams').find(`option[value=${selectedHomeTeamId}]`).prop('selected', 'selected');
                $('#away-teams').find(`option[value=${selectedAwayTeamId}]`).prop('selected', 'selected');
            });
        });

        $('#home-teams').change(function () {
            homeTeamId = Number($(this).find('option:selected').val());

            if (awayTeamId === null) {
                $('#away-teams').empty();
                $('#away-teams').append($('<option>')
                    .text('Select away team...')
                    .prop('selected', 'selected'));

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== homeTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#away-teams').append($(currentOption));
                    }
                });
            } else {
                $('#away-teams').empty();

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== homeTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#away-teams').append($(currentOption));
                    }
                });
                $('#away-teams').find(`option[value=${awayTeamId}]`).prop('selected', 'selected');
            }
        });

        $('#away-teams').change(function () {
            awayTeamId = Number($(this).find('option:selected').val());

            if (homeTeamId === null) {
                $('#home-teams').empty();
                $('#home-teams').append($('<option>')
                    .text('Select home team...')
                    .prop('selected', 'selected'));

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== awayTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#home-teams').append($(currentOption));
                    }
                });
            } else {
                $('#home-teams').empty();

                $.each(availableTeams, function (index, value) {
                    let currentTeam = value;

                    if (Number(currentTeam.id) !== awayTeamId) {
                        let currentOption = $('<option>')
                            .text(currentTeam.name)
                            .val(currentTeam.id);

                        $('#home-teams').append($(currentOption));
                    }
                });
                $('#home-teams').find(`option[value=${homeTeamId}]`).prop('selected', 'selected');
            }
        });
    </script>
}

FootballLeague.App/Areas/Admin/Views/Match/List.cshtml
@model IList<FootballLeague.Common.ViewModels.MatchViewModel>
@{
    ViewData["Title"] = "List";
}

@{
    var isAdmin = User.IsInRole("Admin");
    Layout = isAdmin ? "../Shared/_Layout.cshtml" : "~/Views/Shared/_Layout.cshtml";
}

<section>
    <div class="details-container">
        @{
            var matchDays = Model.Select(x => x.Date).Distinct().ToList();

            for (int i = 0; i < matchDays.Count; i++)
            {
                var currentDay = matchDays[i];
                var matchesByDay = Model.Where(x => x.Date == currentDay).ToList();

                <div class="row">
                    <div class="col-md-8 col-md-offset-2 details" style="text-align: center">
                        <h2>@currentDay.ToShortDateString()</h2>
                    </div>
                </div>
                for (int j = 0; j < matchesByDay.Count; j++)
                {
                    @Html.DisplayFor(x => matchesByDay[j])
                }
            }
        }
    </div>
</section>